# Travis-CI Build for nuget
# see travis-ci.org for details
# Config copied and modified from lib2gitsharp project. (Thanks guys!)

language: c
      
# Make sure CMake is installed
install:
 - sudo apt-get install cmake mono-devel mono-gmcs

# Run the Build script
script:
 - git submodule update --init
 - ./build.sh
# Run Tests
# after_script:

# Only watch the development branch
branches:
 only:
   - master
   
# Notify development list when needed
notifications:
 recipients:
    - atheken@gmail.com
 email:
   on_success: change
   on_failure: always